Taskfile.yml

On the kernel server, `.0` is omitted.

Fix 404 when downloading kernel (on versions ending with '.0')

---

README.md

Instead of running escaped command lines through "sudo -c", better use
the "sudo tee" idiom. This has fewer surprises if something does wrong
with the escaping.

"sudo tee" is probably a better idiom

---

README.md

The libSDL2 version containing the fix is not yet released. But the
version number was quite a bit off in the future anyways. Let's fix it
and also clear up that you won't find the device version number in
dmesg.

Fix the mentioned libSDL2 version number

---

docs/README.md

If you updated the firmware of your Raspberry Pi with the rpi-update tool, the new kernel sources may not be in the official raspberrypi-kernel-headers package yet. It takes some weeks or even months for them to be updated. The linked rpi-src tool will download the appropriate kernel sources directly to your raspberry pi.

Updated README.md for Raspbian

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/DEBUGGING.md
docs/README.md
docs/SECUREBOOT.md
docs/index.md
misc/module-signing/dkms-sign-module
misc/module-signing/one-time-setup
misc/module-signing/sign-modules

In this PR, I document how to make xpadneo and Secure Boot get along.
I added a small note to the README.md, and a longer description to a SECUREBOOT.md file which I included in index.md.
I also added the three helper scripts to the misc/ folder. They are modified so that signing is fully automatic (i.e. passwordless).
I wanted to make some modifications to DEBUGGING.md and bug_report.md in another PR, but since I already committed them to master I did not find how to split it in another PR...
My gripe was that 
- `head -1 "/sys/kernel/debug/hid/0005:045E:<TAB>/rdesc" | tee /dev/tty | cksum` could not be copy-pasted even when I ran it directly as root like you suggested. I think a command using `find` will be more robust.
Finally, I said that Secure Boot could not be disabled on ARM …

Document how to get xpadneo to work with Secure Boot

---

hid-xpadneo/src/hid-xpadneo.c

Build was broken in 5.4. This should fix it.
I tested this on mainline 5.4-rc1 and it worked fine, haven't tested on anything else, but since the hid_dbg macro was not affected by the commit mentioned, it should work fine for older kernels as well.

Fix build and debug print for kernel version >= 5.4

---

lib/installer.sh

Fixes: https://github.com/atar-axis/xpadneo/issues/188

installer: Use awk in non-GNU mode

---

hid-xpadneo/dkms.post_install

When running the install script, the following error is displayed:
`/var/lib/dkms/hid-xpadneo/0.7/source/dkms.post_install: 5: [: unexpected operator`
After analysing `dkms.post_install` with the `shellcheck` utility, the following error is found:
```
$ shellcheck /var/lib/dkms/hid-xpadneo/0.7/source/dkms.post_install
In /var/lib/dkms/hid-xpadneo/0.7/source/dkms.post_install line 5:
if [ "$(readlink "${ERTM_OVERRIDE}")" == "/dev/null" ]; then
^-- SC2039: In POSIX sh, == in place of = is undefined.
```
As stated in the relevant [shellcheck documentation of SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039#testing-equality), `==` operator is not supported in POSIX `sh`, which is being used, as stated on the first "shebang" line of the script.
I have therefore modified the line …

Fix error "/var/lib/dkms/hid-xpadneo/0.7/source/dkms.post_install: 5: [: unexpected operator" when running install script

---

hid-xpadneo/src/hid-xpadneo.c

While reading through the code I noticed that the formatting didn't seem entirely consistent. Not sure if patches like this are accepted, but I threw this together anyways.

Always use curly braces and breaks out of switch cases.

---

hid-xpadneo/src/hid-xpadneo.c

Maybe-fixes: https://github.com/atar-axis/xpadneo/issues/189

hid_xpadneo, rumble: Optimize motor reprogramming

---

hid-xpadneo/src/hid-xpadneo.c

This should match any 8BitDo controller.
Closes: https://github.com/atar-axis/xpadneo/pull/200

hid_xpadneo, quirks: Migrate 8BitDo quirks to OUI match

---

hid-xpadneo/src/hid-xpadneo.c

Rumble protocol throttling and concurrency fixups

---

docs/README.md

Package for headers have slightly different name for Manjaro (as it was figured in #119). So I suggest to put explicit instruction in the README.

Add install instruction for Manjaro

---

NEWS.md
configure.sh
docs/CONFIGURATION.md
docs/config_help
hid-xpadneo/src/hid-xpadneo.c

This is not actually a fix but a replacement through a new feature.
Rumble attenuation can now be controller with the `rumble_attenuation` parameter in percent, i.e. putting 100 as the percentage value means full attenuation aka "no rumble at all".

Fix regression of not being able to disable rumbling

---

hid-xpadneo/etc-udev-rules.d/98-xpadneo.rules

This is a bug in the `libinput` device class detection and would create
an error log per pressed button. We can force `libinput` to ignore the
controller but this does not fix the underlying bug. But it also seems
to introduce no regressions: The Xbox logo button still works.
Fixes: https://github.com/atar-axis/xpadneo/issues/205

xpadneo, udev: Work around libinput using the controller as touchpad

---

configure.sh
docs/CONFIGURATION.md
docs/README.md
hid-xpadneo/src/hid-xpadneo.c

Evidence shows that there is a problematic code path between the Linux kernel and games when using Wine/Proton. Windows games do not expect the input drivers to have dead zones applied but Linux drivers imply that at every level. Since Wine/Proton uses SDL for creating a bus device, it will see a game controller with dead zones already handled - which games do not expect.
This series of commits shrinks the default dead zones and fuzz filter for more precision and adds a kill switch for disabling handling of dead zones completely so Wine/Proton games will have their expectations fulfilled.

Rework dead zone handling

---

configure.sh
docs/CONFIGURATION.md
docs/config_help
hid-xpadneo/src/hid-xpadneo.c

Instead of combining both axis and thus removing the original trigger
function, we can expose a synthesized axis that is built from both the
triggers combined.
See-also: https://github.com/atar-axis/xpadneo/issues/63
Closes: https://github.com/atar-axis/xpadneo/issues/221

hid-xpadneo: Replace `combined_z_axis` with additional axis

---

docs/descriptors/xbxs.md
hid-xpadneo/src/hid-xpadneo.c

It looks like XBXS controllers are shipped using two different OUIs, one of those conflicts with the XBE2 controller. Detect the device quirk by PID instead.
Fixes: https://github.com/atar-axis/xpadneo/issues/268

hid-xpadneo: Move share button quirk to `xpadneo_devices` database

---

docs/README.md

This replaces the Ko-fi link to attribute new donations to the current maintainer Kai Krakow instead of Florian Dollinger, suggested and requested by Florian.

docs: Replace Ko-fi link to attribute donations to current maintainer

---

hid-xpadneo/dkms.post_install

Removed disabling of ERTM only from dkms.post_install, I left dkms.post_remove alone. Reasoning for this was, that user could have installed xpadneo on older kernel, updated their kernel to 5.12 or later, and did an "sudo ./update.sh", which has to remove old ERTM override.

Don't disable ERTM if kernel 5.12 or later

---

hid-xpadneo/etc-udev-rules.d/50-xpadneo-fixup-steamlink.rules

Also fixes Steam Input which apparently also uses SDL2.
The bug shows up when SDL identifies the controller as being on USB
instead of Bluetooth (SDL Gamepad ID starts with `03` instead of `05`)
which then messes with SDL's expectations for the contents of hidraw.
This fixes two SDL problems:
* Wrong mappings in hidraw (buttons shifted to other buttons)
* SDL2 doesn't properly throttle rumble commands (endless rumble)
See-also: https://github.com/atar-axis/xpadneo/issues/286
Maybe-fixes: https://github.com/atar-axis/xpadneo/issues/303
Maybe-fixes: https://github.com/atar-axis/xpadneo/issues/311
Maybe-fixes: https://github.com/atar-axis/xpadneo/issues/314

xpadneo, hidraw: Also work around SDL2 hidraw mode conflicts

---

install.sh
uninstall.sh

DKMS 3 requires passing the version to BOTH the install and uninstall phase and we omitted it from the install phase.

dkms: Explicitly add version to the install phase

---

hid-xpadneo/etc-modprobe.d/xpadneo.conf
hid-xpadneo/etc-udev-rules.d/60-xpadneo.rules
hid-xpadneo/src/hid-xpadneo.c

Microsoft added BLE support to existing controllers.
This PR adds support for binding xpadneo to controllers flashed with the new firmware version which exposes the device under a new PID. It is still work in progress as we may add mapping fixups and quirk handling.

Add support for XB1S BLE firmware update

---

docs/README.md

Fedora does not build a `kernel-headers` package for each release of the kernel, so you can't just use `uname -r` to install it.  Installing just the `kernel-headers` package is sufficient.  This is slightly confusing to people coming from other distros.  The `kernel-headers` package only includes files used to build userspace software, so it doesn't need to track the kernel closely.
The `kernel-devel` does track the kernel, so that is appropriate to install using `uname -r`.

README.md: Fedora instructions are incorrect

---

docs/README.md

Antergos has been discontinued and succeeded by EndeavorOS.

Replaced Antergos with EndeavorOS

---

docs/README.md

Fixes #429.
Amend profile switching documentation to state that profiles set to an Xbox Elite Series 2 controller using the Xbox Accessories app will load and operate correctly. Slots without set configurations inherit the default profile's behavior.

docs(#429): Elite S2 Profiles carry over

---

configure.sh
docs/config_help

I missed this option after encountering the #444 bug, where the controller's vibration stops working. I also think it would be a good idea to set it to 'disabled' by default while the bug persists, as I find it very annoying. I'm not sure about your thoughts on this.
I would fix it myself, but I wouldn't know where to start. Thanks!

Add ff_connect_notify config option to configure.sh

---

hid-xpadneo/src/hid-xpadneo.c

This fix ensures that the missing_reported flag is correctly updated when the keyboard or gamepad is not detected.

xpadneo: Fix missing report check

---

docs/README.md

Added `and NS39 (aka KK3 MAX, firmware v3.6)` so future searches might find this info.
Tested only with Linux 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

Doc update for KK3 Max

---

docs/README.md
docs/heuristics/gamesir-nova.md
hid-xpadneo/src/hid-xpadneo.c
hid-xpadneo/src/xpadneo.h

This family of controllers doesn't support trigger rumble but still needs all the motor-enable bits set unconditionally.
Fixes: https://github.com/atar-axis/xpadneo/issues/484

core, quirks: Add GameSir T4 Nova Lite support

---

Makefile
azure-pipelines.yml
docs/PACKAGING.md
docs/README.md
docs/index.md
hid-xpadneo/Makefile
install.sh
lib/installer.sh
lib/options.sh
uninstall.sh

Rework DKMS integration

---

docs/README.md

* Use dlundqvist xone fork (which is also used on AUR), since the original one by medusalix is not active anymore and also doesn't build on newer kernels
* Mark xow as unmaintained since it hasn't received updates for many years and also doesn't build on newer kernels

xpadneo, docs: Update links to other projects
